#pragma once

// ── TFT panel selection ───────────────────────────────────────────────────
// Default: ST7789 320×240 landscape (e.g. 2.4" IPS, Adafruit P/N 4311).
// To swap to a different ST7789 variant, just change the constructor args
// in begin() and the TFT_W/TFT_H defines in Config.h.

#include <Adafruit_GFX.h>
#include <Adafruit_ST7789.h>
#include <SPI.h>
#include <Fonts/FreeMonoBold9pt7b.h>
#include <Fonts/FreeMono9pt7b.h>
#include "Config.h"

// The colour logo header is generated by tools/png-to-rgb565.py from a
// user-supplied PNG. Until it's generated we fall back to the 1-bit
// JellyboxLogo drawn in the accent colour so the firmware compiles and
// runs immediately.
#if __has_include("JellyboxLogoColor.h")
  #include "JellyboxLogoColor.h"
  #define JELLYBOX_HAS_COLOR_LOGO 1
#else
  #include "JellyboxLogo.h"
#endif

namespace tft_color {
  constexpr uint16_t BG      = 0xFFFF;  // white
  constexpr uint16_t TEXT    = 0x0000;  // black
  constexpr uint16_t MUTED   = 0x8410;  // mid-grey for hint text
  constexpr uint16_t ACCENT  = 0x435C;  // jf-primary blue (matches dashboard)
  constexpr uint16_t SUCCESS = 0x0660;  // jf-success green
  constexpr uint16_t ERR     = 0xF800;  // red
  constexpr uint16_t SCAN    = 0x9933;  // purple (matches scan-mode LED)
}

using Panel = Adafruit_ST7789;

class TFTDisplay {
public:
  TFTDisplay()
    : _display(PIN_TFT_CS, PIN_TFT_DC, PIN_TFT_RST)
  {}

  void begin() {
    _display.init(240, 320);
    _display.setRotation(1);          // landscape: 320×240
    _display.setTextWrap(false);
    _display.setTextColor(tft_color::TEXT, tft_color::BG);
    _clear();
  }

  // Startup splash — colour logo centred with "JELLYBOX" title below.
  void showSplash() {
    _clear();
    _drawLogo(/* yTop */ 18);
    _setColor(tft_color::ACCENT);
    _centre("JELLYBOX", &FreeMonoBold9pt7b, 200);
  }

  void showUnpaired() {
    _clear();
    _title("JELLYBOX");
    _divider(60);
    _setColor(tft_color::TEXT);
    _centre("Unpaired - connect to:", nullptr, 100);
    _setColor(tft_color::ACCENT);
    _centre(WIFI_AP_NAME, &FreeMonoBold9pt7b, 140);
    _setColor(tft_color::MUTED);
    _centre("to configure", nullptr, 180);
  }

  void showConnecting(const String& ssid = "") {
    _clear();
    _title("JELLYBOX");
    _divider(60);
    _setColor(tft_color::TEXT);
    if (ssid.length() > 0) {
      _centre("Connecting to:", nullptr, 110);
      _setColor(tft_color::ACCENT);
      _centre(_trunc(ssid, 22).c_str(), &FreeMonoBold9pt7b, 150);
    } else {
      _centre("Connecting...", &FreeMono9pt7b, 130);
    }
    _setColor(tft_color::MUTED);
    _centre((String("fw ") + FIRMWARE_VERSION).c_str(), nullptr, 220);
  }

  // Ready / idle screen — colour logo + device name. Unlike the eInk
  // panel, the TFT clears to white on power-off, so there's no ambiguity
  // between "powered idle" and "off" — we can use the same minimalist
  // layout without misleading anyone.
  void showReady(const String& name) {
    _clear();
    _drawLogo(/* yTop */ 18);
    _setColor(tft_color::TEXT);
    _centre(_trunc(name, 22).c_str(), &FreeMonoBold9pt7b, 200);
  }

  void showScanMode(const String& name) {
    _clear();
    _title("JELLYBOX");
    _divider(60);
    _setColor(tft_color::TEXT);
    _centre(_trunc(name, 22).c_str(), &FreeMonoBold9pt7b, 105);
    _setColor(tft_color::SCAN);
    _centre("[ SCAN MODE ]", &FreeMonoBold9pt7b, 150);
    _setColor(tft_color::MUTED);
    _centre("Scan a tag to register", nullptr, 200);
  }

  void showLastPlayed(const String& name, const String& title) {
    _clear();
    _title("JELLYBOX");
    _divider(60);
    _setColor(tft_color::MUTED);
    _centre(_trunc(name, 22).c_str(), &FreeMono9pt7b, 105);
    _setColor(tft_color::ACCENT);
    _centre("Now playing:", nullptr, 145);
    _setColor(tft_color::TEXT);
    _centre(_trunc(title, 28).c_str(), &FreeMonoBold9pt7b, 185);
  }

  void showError(const String& msg) {
    _clear();
    _title("JELLYBOX");
    _divider(60);
    _setColor(tft_color::ERR);
    _centre("Error", &FreeMonoBold9pt7b, 120);
    _setColor(tft_color::TEXT);
    _centre(_trunc(msg, 30).c_str(), nullptr, 170);
  }

  void showUpdating(const String& fromVersion, const String& toVersion) {
    _clear();
    _title("JELLYBOX");
    _divider(60);
    _setColor(tft_color::ACCENT);
    _centre("Updating firmware", &FreeMonoBold9pt7b, 110);
    String arrow = _trunc(fromVersion, 10) + " -> " + _trunc(toVersion, 10);
    _setColor(tft_color::TEXT);
    _centre(arrow.c_str(), nullptr, 150);
    _setColor(tft_color::MUTED);
    _centre("Do not unplug", nullptr, 200);
  }

  void showUpdateProgress(int percent) {
    if (percent < 0)   percent = 0;
    if (percent > 100) percent = 100;
    _clear();
    _title("JELLYBOX");
    _divider(60);
    _setColor(tft_color::ACCENT);
    _centre("Updating firmware", &FreeMonoBold9pt7b, 110);

    int16_t barX = 40;
    int16_t barW = TFT_W - 80;
    int16_t barY = 145;
    int16_t barH = 22;
    _display.drawRect(barX, barY, barW, barH, tft_color::TEXT);
    int16_t fillW = (int16_t)((int32_t)(barW - 4) * percent / 100);
    _display.fillRect(barX + 2, barY + 2, fillW, barH - 4, tft_color::ACCENT);

    _setColor(tft_color::TEXT);
    String pct = String(percent) + "%";
    _centre(pct.c_str(), nullptr, 200);
  }

  void showUpdateFailed(const String& msg) {
    _clear();
    _title("JELLYBOX");
    _divider(60);
    _setColor(tft_color::ERR);
    _centre("Update failed", &FreeMonoBold9pt7b, 120);
    _setColor(tft_color::TEXT);
    _centre(_trunc(msg, 30).c_str(), nullptr, 170);
  }

private:
  Panel _display;

  void _clear() {
    _display.fillScreen(tft_color::BG);
  }

  void _setColor(uint16_t fg) {
    _display.setTextColor(fg, tft_color::BG);
  }

  void _title(const char* text) {
    _setColor(tft_color::ACCENT);
    _centre(text, &FreeMonoBold9pt7b, 40);
  }

  void _divider(int16_t y) {
    _display.drawFastHLine(20, y, TFT_W - 40, tft_color::ACCENT);
  }

  // Centre text horizontally. y is the text baseline.
  void _centre(const char* text, const GFXfont* font, int16_t y) {
    _display.setFont(font);
    int16_t x1, y1;
    uint16_t w, h;
    _display.getTextBounds(text, 0, y, &x1, &y1, &w, &h);
    int16_t x = (TFT_W - (int16_t)w) / 2 - x1;
    if (x < 4) x = 4;
    _display.setCursor(x, y);
    _display.print(text);
  }

  void _drawLogo(int16_t yTop) {
#ifdef JELLYBOX_HAS_COLOR_LOGO
    int16_t logoX = (TFT_W - (int16_t)JELLYBOX_LOGO_COLOR_W) / 2;
    _display.drawRGBBitmap(
      logoX, yTop, JELLYBOX_LOGO_COLOR, JELLYBOX_LOGO_COLOR_W, JELLYBOX_LOGO_COLOR_H);
#else
    // Fallback: 1-bit logo drawn in the accent colour. Used until the
    // user runs tools/png-to-rgb565.py to generate JellyboxLogoColor.h.
    int16_t logoX = (TFT_W - (int16_t)JELLYBOX_LOGO_W) / 2;
    _display.drawBitmap(
      logoX, yTop, JELLYBOX_LOGO, JELLYBOX_LOGO_W, JELLYBOX_LOGO_H, tft_color::ACCENT);
#endif
  }

  String _trunc(const String& s, size_t maxLen) {
    if (s.length() <= maxLen) return s;
    return s.substring(0, maxLen - 3) + "...";
  }
};
