#!/usr/bin/env python3
"""
Convert a PNG to a 72×72 RGB565 PROGMEM header for the TFT SKU's colour logo.

Usage:
    python tools/png-to-rgb565.py path/to/logo.png > jellybox-firmware/JellyboxLogoColor.h

Requires:
    pip install pillow

The output matches the existing JellyboxLogo.h style (PROGMEM array + width
+ height constants) so TFTDisplay.h includes it via __has_include and uses
drawRGBBitmap. The fallback (1-bit mono logo drawn in the accent colour)
disappears as soon as this header is present.

Resamples to 72×72 with Lanczos, alpha-composites onto white so transparent
PNGs end up white-backgrounded (matching the TFT's background), then packs
each pixel as RGB565 little-endian uint16_t.
"""
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.stderr.write("error: Pillow is required (pip install pillow)\n")
    sys.exit(1)

SIZE = 72


def rgb_to_565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> int:
    if len(sys.argv) != 2:
        sys.stderr.write("usage: png-to-rgb565.py <input.png>\n")
        return 2

    src = Path(sys.argv[1])
    img = Image.open(src).convert("RGBA")

    # Composite onto white so transparent regions match the TFT background.
    white = Image.new("RGBA", img.size, (255, 255, 255, 255))
    img = Image.alpha_composite(white, img).convert("RGB")
    img = img.resize((SIZE, SIZE), Image.LANCZOS)

    pixels = list(img.getdata())  # list of (r, g, b)

    print("#pragma once")
    print("// Generated by tools/png-to-rgb565.py from", src.name)
    print("// Do not hand-edit. Re-run the script to regenerate.")
    print("#include <pgmspace.h>")
    print()
    print(f"static const uint16_t JELLYBOX_LOGO_COLOR_W = {SIZE};")
    print(f"static const uint16_t JELLYBOX_LOGO_COLOR_H = {SIZE};")
    print(f"static const uint16_t JELLYBOX_LOGO_COLOR[{SIZE * SIZE}] PROGMEM = {{")

    # 12 values per row for readable diffs.
    PER_ROW = 12
    for i in range(0, len(pixels), PER_ROW):
        row = pixels[i:i + PER_ROW]
        values = ", ".join(f"0x{rgb_to_565(r, g, b):04X}" for r, g, b in row)
        suffix = "," if i + PER_ROW < len(pixels) else ""
        print(f"  {values}{suffix}")

    print("};")
    return 0


if __name__ == "__main__":
    sys.exit(main())
